### Робота з бібліотекою Numpy
> Після встанолення бібліотеки можливо буде потрібно рестартувати ядро Python, використайте кнопку `Restart`.

In [1]:
def homework(message):
    print("\n>>>>>", message, "\n")

In [2]:
import numpy as np

# Масив температур
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

# Неправильне множення списку
t1 = temperature * 5
print(f"При множенні на 5 маємо: {t1}")
print("Список повторюється п'ять разів, оскільки множення списку в Python не змінює його елементи, а лише повторює його вміст.")

# Коректне множення значень у списку
t1 = [x * 5 for x in temperature]
print(f"Тепер отримаємо: {t1}")
print("Тепер множення успішне, оскільки ми перебираємо кожен елемент списку й множимо його на 5.")

# Масив NumPy
t2 = np.array(temperature)
print("Масив з використанням методів NumPy:", t2)

# Множення NumPy масиву
t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)
print("NumPy масиви дозволяють виконувати операції напряму, застосовуючи їх до всіх елементів масиву, завдяки чому множення працює як очікується.")


[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]
Список повторюється п'ять разів, оскільки множення списку в Python не змінює його елементи, а лише повторює його вміст.
Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]
Тепер множення успішне, оскільки ми перебираємо кожен елемент списку й множимо його на 5.
Масив з використанням методів NumPy: [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]
NumPy масиви дозволяють виконувати операції напряму, застосовуючи їх до всіх елементів масиву, завдяки чому множення працює як очікується.


### Вектори, створення та робота з ними

In [3]:
print("Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:")
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:
[[ 1 -5  3  2  4]] 
Вектор має розмір (1, 5)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


#### Метод arange - генерує послідовність чисел з певним кроком у заданому інтервалі

In [4]:
start = 5
size_of_vec = 100

# Генерація масиву з range та arange
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {list(x)[0:5]} та методом arange: {a[0:5]}")
print("Весь діапазон чисел range:", list(x))
print("Весь діапазон чисел arange:", a)

# Початок генерації вектора
a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
print(f"Останній елемент у згенерованому масиві: {a[-1]}")

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", list(x))
print("Число з середини діапазону (range):", list(x)[len(list(x)) // 2])

# Дробові числа
x = np.arange(10.4)
print("Будемо мати масив:", x)

# Крок 0.5
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)

# Крок 0.08
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x)
print("Зверніть увагу на заокруглення через особливості чисел з плаваючою комою.")

# Згенерувати значення з кроком 0.0001
x = np.arange(0.0001, 0.001, 0.0001)
print("З кроком 0.0001:", x)

# Перемноження масиву
y = x * 2.5
print("Після перемноження на 2.5:", y)

# Піднесення до степеня і ділення
result = (y**2) / 0.4
print("Результат після піднесення до квадрату і ділення на 0.4:", result)


Масив згенерований простим range: [0, 1, 2, 3, 4] та методом arange: [0 1 2 3 4]
Весь діапазон чисел range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Весь діапазон чисел arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Можемо задавати початок генерації вектора, перший елемент: 5
Останній елемент у згенерованому масиві: 99
Те саме але з вбудованою функцією range: [5, 6, 7, 8, 9, 10, 1

#### Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням

In [5]:
start = 5
size_of_vec = 100

# Генерація чисел за допомогою linspace
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні від {a[0]} до {a[-1]}")

# Виведення кожного другого числа з діапазону
print("Кожне друге число згенерованого діапазону:")
for i in range(1, len(a), 2):
    print(a[i])

# Зменшення кількості чисел до 5
print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)

# Збільшення кількості чисел до 100 і виведення перших та останніх 10
a = np.linspace(start, size_of_vec, 100)
print("Перші 10 чисел:", a[:10])
print("Останні 10 чисел:", a[-10:])

# Включення та виключення останнього значення
print("""
Як бачимо, перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно, при цьому вираховується крок. 
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")
print("Без останнього значення:", np.linspace(start, size_of_vec, 5, endpoint=False))

# Автоматичне визначення кроку
_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Крок для включеного останнього значення: {sp_1}")
print(f"Крок для виключеного останнього значення: {sp_2}")

# Причина різних кроків
print("Різний крок через те, що для включеного останнього значення діапазон розподіляється між n-1 проміжками, а для виключеного - між n проміжками.")


Згенерували 50 чисел в діапазоні від 5.0 до 100.0
Кожне друге число згенерованого діапазону:
6.938775510204081
10.816326530612244
14.693877551020408
18.57142857142857
22.448979591836736
26.3265306122449
30.20408163265306
34.08163265306122
37.95918367346939
41.83673469387755
45.714285714285715
49.59183673469388
53.46938775510204
57.3469387755102
61.224489795918366
65.10204081632654
68.9795918367347
72.85714285714286
76.73469387755102
80.61224489795919
84.48979591836735
88.36734693877551
92.24489795918367
96.12244897959184
100.0
Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]
Перші 10 чисел: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.75757576 11.71717172 12.67676768 13.63636364]
Останні 10 чисел: [ 91.36363636  92.32323232  93.28282828  94.24242424  95.2020202
  96.16161616  97.12121212  98.08080808  99.04040404 100.        ]

Як бачимо, перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно, при цьому вира

### Типи масивів/векторів

In [6]:
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2], [3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                         [[211, 212], [221, 222]],
                                         [[311, 312], [321, 322]] ])
}

for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів x: {np.size(examples[key])}")
    print("-=-"*10)

# Створення власних векторів
vector_1 = np.array([10, 20, 30])
vector_2 = np.array([[100], [200], [300]])

print("Власний Вектор Рядок:", vector_1)
print("Розмірність:", np.ndim(vector_1), ", Форма:", vector_1.shape)
print("Власний Вектор Стовпець:\n", vector_2)
print("Розмірність:", np.ndim(vector_2), ", Форма:", vector_2.shape)

# Пояснення розмірності та форми
print("""
Функція np.ndim визначає кількість вимірів (axes) масиву:
- Скаляр має 0 вимірів.
- Вектор Рядок і Вектор Стовпець мають 1 та 2 виміри відповідно, хоча shape вказує на кількість елементів в кожному вимірі.
- Матриці та багатовимірні масиви мають відповідно 2 і більше вимірів.
""")


Розглядаємо приклад з Скаляр. 
Значення x буде: 
 1
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів x: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (3,)
Кількість елементів x: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (3, 1)
Кількість елементів x: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 2)
Кількість елементів x: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[111 112]
  [121 122]]

 [[211 

### Багатовимірні масиви, розуміння вимірів
> Метод np.shape дозволяє зрозуміти виріми масиву і подає їх як (кількість рядків, кількість стовпців, кількість елементів).
Зверніть увагу на кількість квадратних дужок!!

In [7]:
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]), 
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів у вкладеному масиві': np.array([[[1, 2, 3, 4, 5]]])
}

for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}")
    print("-=-" * 10)

# Створення власних масивів
custom_array_1 = np.array([1, 2, 3, 4])  # Одновимірний масив
custom_array_2 = np.array([[1, 2], [3, 4], [5, 6]])  # Двовимірний масив
custom_array_3 = np.array([[[1, 2]], [[3, 4]], [[5, 6]]])  # Тривимірний масив

print("Власний одновимірний масив:")
print("Масив:", custom_array_1, ", shape:", custom_array_1.shape)

print("Власний двовимірний масив:")
print("Масив:\n", custom_array_2, ", shape:", custom_array_2.shape)

print("Власний тривимірний масив:")
print("Масив:\n", custom_array_3, ", shape:", custom_array_3.shape)


Для 5 рядків маємо shape: 
(5, 1) 
та вигляд: 
[[1]
 [2]
 [3]
 [4]
 [5]]
-=--=--=--=--=--=--=--=--=--=-
Для 5 стовпців маємо shape: 
(1, 5) 
та вигляд: 
[[1 2 3 4 5]]
-=--=--=--=--=--=--=--=--=--=-
Для 5 елементів у вкладеному масиві маємо shape: 
(1, 1, 5) 
та вигляд: 
[[[1 2 3 4 5]]]
-=--=--=--=--=--=--=--=--=--=-
Власний одновимірний масив:
Масив: [1 2 3 4] , shape: (4,)
Власний двовимірний масив:
Масив:
 [[1 2]
 [3 4]
 [5 6]] , shape: (3, 2)
Власний тривимірний масив:
Масив:
 [[[1 2]]

 [[3 4]]

 [[5 6]]] , shape: (3, 1, 2)


### Indexing and Slicing
> для доступу до елементів масиву використовуються Indexing, а якщо потрібно доступитись до декількох елементів зразу Slicing.

In [8]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(f"""Масив: {F}
Виміри: {F.shape}
Пам’ятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву: {F[0]}
Другий: {F[1]}
Останній, {len(F)}: {F[7]}""")

print(f"""Можемо скористатись від’ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент: {F[-1]}
Передостанній: {F[-2]}""")

# Доступ до елементів різними способами
print("Декілька елементів за допомогою зрізу (slice):", F[2:5])  # Елементи з індексами 2, 3, 4
print("Кожен другий елемент масиву:", F[::2])  # Крок через 2 елементи
print("Елементи у зворотному порядку:", F[::-1])  # Реверс масиву


Масив: [ 1  1  2  3  5  8 13 21]
Виміри: (8,)
Пам’ятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву: 1
Другий: 1
Останній, 8: 21
Можемо скористатись від’ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент: 21
Передостанній: 13
Декілька елементів за допомогою зрізу (slice): [2 3 5]
Кожен другий елемент масиву: [ 1  2  5 13]
Елементи у зворотному порядку: [21 13  8  5  3  2  1  1]


In [9]:
A = np.array([[3.4, 8.7, 9.9], 
              [1.1, -7.8, -0.7],
              [4.1, 12.3, 4.8],
              [7.0, -3.9, 5.1]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення, то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

# Доступ до елементів, що належать діагоналі
diagonal_elements = [A[i, i] for i in range(min(A.shape))]
print("Елементи діагоналі масиву A:", diagonal_elements)

# Альтернативний спосіб за допомогою np.diagonal()
diagonal_np = np.diagonal(A)
print("Елементи діагоналі через np.diagonal():", diagonal_np)


Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри: (4, 3)
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення, то візьметься цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: 3.4 або 3.4
    Останній елемент: 5.1 або 5.1 або 5.1

Елементи діагоналі масиву A: [np.float64(3.4), np.float64(-7.8), np.float64(4.8)]
Елементи діагоналі через np.diagonal(): [ 3.4 -7.8  4.8]


> Для доступу до декількох елементів використовують Slicing. 
Принцип доступу до елементів  S[start:stop:step]. 
Елемент stop не включається у вивід.

In [10]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")

# Витягування 4 значень з кінця масиву
last_four_elements = S[-4:]
print("Останні 4 елементи масиву:", last_four_elements)


Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]

Останні 4 елементи масиву: [6 7 8 9]


> Такий самий принцип Slicing може використовуватись для багатовимірних масивів.

In [11]:
A = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків: 
{A[0:2]}
Два перші стовпці: 
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи): 
{A[-3:, -3:]}
""")

# Витягування матриці 2х2 з нижнього кута
lower_corner = A[-2:, -2:]
print("Матриця 2х2 з нижнього кута:")
print(lower_corner)

# Витягування матриці 2х2 з верхнього кута
upper_corner = A[:2, :2]
print("Матриця 2х2 з верхнього кута:")
print(upper_corner)


Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри: (5, 5)
Беремо декілька рядків: 
[[11 12 13 14 15]
 [21 22 23 24 25]]
Два перші стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]
Два останні рядки:
[[41 42 43 44 45]
 [51 52 53 54 55]]
Беремо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]

Матриця 2х2 з нижнього кута:
[[44 45]
 [54 55]]
Матриця 2х2 з верхнього кута:
[[11 12]
 [21 22]]


> Slicing дозволяє брати не тільки послідовні значення але із заданим кроком.

In [12]:
A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен другий елемент першого рядка: 
{A[0, ::2]}
Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}
Кожен другий елемент в кожному другому рядку: 
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повністю змінити порядок елементів (дзеркально обернемо):
{A[::-1, ::-1]}
""")

# Приклад комбінації: кожен третій елемент із останніх двох рядків
custom_selection = A[-2:, ::3]
print("Вибрані елементи (кожен третій елемент із останніх двох рядків):")
print(custom_selection)


Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен другий елемент першого рядка: 
[0 2 4 6]
Беремо кожен третій елемент першого рядка: 
[0 3 6]
Кожен другий елемент в кожному другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]
Можна повністю змінити порядок елементів (дзеркально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]

Вибрані елементи (кожен третій елемент із останніх двох рядків):
[[14 17 20]
 [21 24 27]]


> можна здійснювати вибірку елементів по умові

In [13]:
A = np.arange(50)
all_even = (A % 2 == 0)  # парні
complex = (A < 30) & (A / 5 < 2)

print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувавти більш комплексну умову з двох порівнянь:
{A[complex]}""")

# Виведення непарних чисел
all_odd = (A % 2 != 0)  # непарні
print("Непарні числа з масиву:")
print(A[all_odd])


Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувавти більш комплексну умову з двох порівнянь:
[0 1 2 3 4 5 6 7 8 9]
Непарні числа з масиву:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


### Функції для створення матриць: ones, zeros, identity, eye, empty

In [14]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
{t}
""")



Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.11261162e-306
 3.27034156e-317]

